import Head from 'next/head'
import Link from 'next/link'

export default function Home({ data }) {
  console.log(data)
  const elements = data.map((el,i) => {
    return (
      <h1 key={i}>{el.name}</h1>
    )
  })
  return (
    <>
      <Head>
        <title>E-shop Browser</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {elements}
      </main>
    </>
  )
}

export async function getStaticProps() {
  const url = `https://api.igdb.com/v4/games/`
  const options = {
    method: 'POST',
    headers: {
      'Client-ID': process.env.CLIENT_ID,
      'Authorization': process.env.AUTHORIZATION
    },
    body: "fields *; where id = 1942;"
  }
  const res = await fetch(url, options)
  const data = await res.json()
  return {
    props: {
      data: data
    }
  }
}
